name       : ibus-chewing
version    : 1.5.1
release    : 2
source     :
    - https://github.com/definite/ibus-chewing/releases/download/1.5.1/ibus-chewing-1.5.1-Source.tar.gz : 687ce9f09fef31b0e31ad0d2f1be17f1ca0b9212af9d71812cf53d84a90f0060
license    : GPL-2.0
component  : desktop.core
summary    : IBus-Chewing is an IBus front-end of Chewing, an intelligent Chinese input method for Zhuyin (BoPoMoFo) users
description: |
    Bus-Chewing is an IBus front-end of Chewing, an intelligent Chinese input method for Zhuyin (BoPoMoFo) users
builddeps  :
    - pkgconfig(chewing)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(ibus-1.0)
    - pkgconfig(x11)
    - gob2
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
